name: Build (Linux cross-compile)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-component.yml
    with:
      artifact-name: foo_qobuz-linux-cross
